import {
  AGENT_OPTIONS,
  PACKAGE_OPTIONS,
  MODEM_OPTIONS,
  PAY_METHOD_OPTIONS,
  SR_TYPE_OPTIONS,
  PENDING_ASSIGNED_OPTIONS,
  YES_NO_OPTIONS,
} from "./datasetColumns";

export const acceptsColumns = [
  { key: "landline", label: "Landline" },
  { key: "name", label: "Name" },
  { key: "contact", label: "Contact" },
  { key: "agent", label: "Agent", type: "select", options: AGENT_OPTIONS },
  { key: "agentNotes", label: "Agent notes" },
  { key: "address", label: "Address" },
  { key: "landlineOwner", label: "Landline owner" },
  { key: "modem", label: "Modem", type: "select", options: MODEM_OPTIONS },
  { key: "payMethod", label: "Installment/Cash", type: "select", options: PAY_METHOD_OPTIONS },
  { key: "packageName", label: "Package name", type: "select", options: PACKAGE_OPTIONS },
  { key: "status", label: "Status" },
  { key: "dataType", label: "Data type" },
  { key: "investigation", label: "Investigation" },
  { key: "landlineRing", label: "Landline ring?", type: "select", options: YES_NO_OPTIONS },
  { key: "srVoda", label: "SR Voda" },
  { key: "gsm", label: "GSM" },
  { key: "acceptDate", label: "Accept date", type: "date" },
  { key: "visitDate", label: "Visit date", type: "date" },
  { key: "customerId", label: "Customer ID" },
  { key: "followUpNotes", label: "Follow up notes" },
  { key: "naField", label: "N/A" },
  { key: "pendingOrAssigned", label: "Pending/Assigned", type: "select", options: PENDING_ASSIGNED_OPTIONS },
  { key: "furtherNotes", label: "Further notes" },
];

export const creationColumns = [
  { key: "landline", label: "Landline" },
  { key: "name", label: "Name" },
  { key: "contact", label: "Contact" },
  { key: "agent", label: "Agent", type: "select", options: AGENT_OPTIONS },
  { key: "agentNotes", label: "Agent notes" },
  { key: "dataType", label: "Data type" },
  { key: "applyPhone", label: "Apply phone" },
  { key: "srType", label: "Red/Normal", type: "select", options: SR_TYPE_OPTIONS },
  { key: "srEt", label: "SR ET" },
  { key: "srVod", label: "SR Vod" },
  { key: "furtherNotes", label: "Further notes" },
];
